format = """$character"""

right_format = """
$directory\
$git_branch\
"""

[directory]
style = "gray"

[character]
success_symbol = "[\\$](green)"
error_symbol = "[\\$](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"
